# Generated by Django 4.0.3 on 2022-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_post_snippest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippest',
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click link above', max_length=255),
        ),
    ]
